<?php
/**
 * Created by PhpStorm.
 * User: elex
 * Date: 16.09.18
 * Time: 12:04
 */

namespace OCA\SensorLogger;


class LogOwntrack extends LogExtended
{
    protected $_type;
    protected $acc;
    protected $alt;
    protected $batt;
    protected $cog;
    protected $desc;
    protected $event;
    protected $lat;
    protected $lon;
    protected $rad;
    protected $t;
    protected $tid;
    protected $tst;
    protected $vac;
    protected $vel;
    protected $p;
    protected $conn;

    public function __construct($data)
    {
        parent::__construct($data);
        $this->addType('dataTypeId', 'integer');
        $this->addType('value', 'float');
        //$this->acc = $data->acc;
        //$this->dataTypeId = $data->dataTypeId;
        //$this->value = $data->value;
        //$this->short = $data->short;
        //$this->type = $data->type;
    }

    /**
     * @return mixed
     */
    public function getAcc()
    {
        return $this->acc;
    }

    /**
     * @param mixed $acc
     */
    public function setAcc($acc)
    {
        $this->acc = $acc;
    }

    /**
     * @return mixed
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
     * @param mixed $alt
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;
    }

    /**
     * @return mixed
     */
    public function getBatt()
    {
        return $this->batt;
    }

    /**
     * @param mixed $batt
     */
    public function setBatt($batt)
    {
        $this->batt = $batt;
    }

    /**
     * @return mixed
     */
    public function getCog()
    {
        return $this->cog;
    }

    /**
     * @param mixed $cog
     */
    public function setCog($cog)
    {
        $this->cog = $cog;
    }

    public function getDescription()
    {
        return parent::getDescription(); // TODO: Change the autogenerated stub
    }

    public function setDescription($description)
    {
        parent::setDescription($description); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * @param mixed $event
     */
    public function setEvent($event)
    {
        $this->event = $event;
    }

    /**
     * @return mixed
     */
    public function getLon()
    {
        return $this->lon;
    }

    /**
     * @param mixed $lon
     */
    public function setLon($lon)
    {
        $this->lon = $lon;
    }

    /**
     * @return mixed
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * @param mixed $lat
     */
    public function setLat($lat)
    {
        $this->lat = $lat;
    }

    /**
     * @return mixed
     */
    public function getRad()
    {
        return $this->rad;
    }

    /**
     * @param mixed $rad
     */
    public function setRad($rad)
    {
        $this->rad = $rad;
    }

    /**
     * @return mixed
     */
    public function getT()
    {
        return $this->t;
    }

    /**
     * @param mixed $t
     */
    public function setT($t)
    {
        $this->t = $t;
    }

    /**
     * @param mixed $tid
     */
    public function setTid($tid)
    {
        $this->tid = $tid;
    }

    /**
     * @return mixed
     */
    public function getTid()
    {
        return $this->tid;
    }

    /**
     * @return mixed
     */
    public function getTst()
    {
        return $this->tst;
    }

    /**
     * @param mixed $tst
     */
    public function setTst($tst)
    {
        $this->tst = $tst;
    }

    /**
     * @return mixed
     */
    public function getVac()
    {
        return $this->vac;
    }

    /**
     * @param mixed $vac
     */
    public function setVac($vac)
    {
        $this->vac = $vac;
    }

    /**
     * @return mixed
     */
    public function getVel()
    {
        return $this->vel;
    }

    /**
     * @param mixed $vel
     */
    public function setVel($vel)
    {
        $this->vel = $vel;
    }

    /**
     * @return mixed
     */
    public function getP()
    {
        return $this->p;
    }

    /**
     * @param mixed $p
     */
    public function setP($p)
    {
        $this->p = $p;
    }

    /**
     * @return mixed
     */
    public function getConn()
    {
        return $this->conn;
    }

    /**
     * @param mixed $conn
     */
    public function setConn($conn)
    {
        $this->conn = $conn;
    }

}